### ISSUE TITLE
Instalation error 12.0.1 ATM 19.1

### ISSUE THREAD

**Issue by cybercuate** [crc-32/BrowseNX#23]
Error: 2356-0002 (0x564)
Module: Goldleaf (356)
Description: NCA metadata is missing

I can install games with sig-patches and everything except BrowseNX NSP

**Comment by LauraWebdev** [comment]
Similar problems on 12.1.0, I guess this needs to be rebuild for newer versions?

**Comment by crc-32** [comment]
NSP will no longer be supported going forward as there's no real advantage on newest Atmosphere

**Comment by LauraWebdev** [comment]
The way to go would be to build a forwarder NSP then?
