### ISSUE TITLE
NSP install error

### ISSUE THREAD

**Issue by ColbzDaBoss** [crc-32/BrowseNX#25]
Attempting to install the latest NSP on Atmosphere 12.1 returns an error: can't find nca header. Any help would be appreciated UwU :3

**Comment by SonsofOcelot** [comment]
Same issue. Trying to install using the latest update of Goldleaf on Atmosphere 0.20.1 fw 12.1 and get:

Error: 2356-0002 (0x564)
Module: Goldleaf (356)
Description: The metadata NCA could not be located in the NSP (2)

**Comment by crc-32** [comment]
NSP will no longer be supported going forward as there's no real advantage on newest Atmosphere
