### ISSUE TITLE
Guide to install

### ISSUE THREAD

**Issue by kamigreed** [crc-32/BrowseNX#26]
Sorry if this is dumb, how do I install this? I tried the nro from hbgshop, managed to launch the app while holding R and launching it via hbmenu, but it keeps closing.... Or do I just delete that nro and download this nsp? Tq

**Comment by Masamune3210** [comment]
Try downloading the nro straight from here, hbgshop hasnt been a thing for a while now

**Comment by kamigreed** [comment]
Thanks, for someone new to the scene, I didn't know that. NRO still doesn't work for me, but I found out the NSP did. Though I can't play NETFLIX or anime vids with it. Thanks.
