### ISSUE TITLE
hb appstore

### ISSUE THREAD

**Issue by Skalke** [crc-32/BrowseNX#5]
will u add this stuff in hb appstore?

**Comment by crc-32** [comment]
If you mean will it be installable from there, maybe in the future (hb appstore doesn't work with NSPs currently and this is an NSP only app at the moment)
If you mean will this functionality be added to the hb appstore, no

**Comment by crc-32** [comment]
The appstore is currently nro only cause thats the only thing it is made to install (or anything where you just put something in a folder)
Its not that its not allowed its just that you would need to install it manually which might confuse people (it'd just download to root of SD and you'd need to have goldleaf and open it for an install)

**Comment by Skalke** [comment]
i know that....but why we need this if we have goldleaf.nsp with that tool? and confising is'nt problem if installation quick quide will be in description in page of hb appstore

**Comment by crc-32** [comment]
This is a direct launcher instead of going through Goldleaf, also will have more features (bear in mind we're only on v0.1.1) that make it more browser-like in the future.
Might be added to hbappstore soonTM depending on future features of the store.
