### ISSUE TITLE
Nsp error

### ISSUE THREAD

**Issue by Kronos2308** [crc-32/BrowseNX#8]
Its maybe my problem, but when i try to compile the source code i get a nsp that can't be installed on the switch

**Comment by crc-32** [comment]
Maybe provide more information so I can help?

**Comment by Kronos2308** [comment]
Ok
I take the source code from the github
Put my prod.keys 
And run the .bat that's give me no errors but when i try to intall that nsp all the instaler say, error , not valid ,ctm , but if i toke the nsp from the release have no trouble

**Comment by crc-32** [comment]
Interesting, I occasionally had this error before but attempting to install the nsp again worked. Try that, and if it doesn't then it seems the bat or windows building needs fixes.
