### ISSUE TITLE
Supernag patch isnt working?

### ISSUE THREAD

**Issue by Rokutiz** [crc-32/BrowseNX#9]
Installed the atmosphere folder included with browsenx.zip file.
I even have 90dns setup with the switch.
browsenx.nsp still says supernag active. The fuck?

**Comment by hunter3035** [comment]
I'm having this issue as well. I'm running ReINX 2.0 on firmware 6.2.

**Comment by hunter3035** [comment]
It isn't working for me on the latest version of Atmosphere either. I can use 0.2.0 just fine because of the lack of supernag contingency.

**Comment by crc-32** [comment]
So you're saying the version without the extra supernag check in the app
works? Maybe it bypasses the sysmodule or something... I'll work on a fix

**Comment by crc-32** [comment]
Can someone else confirm also that running pre-supernag contingency version but with the sysmodule (atmosphere folder) still installed allows them to use the app...?

**Comment by Rokutiz** [comment]
I can confirm. previous version works with sysmodule installed.

**Comment by crc-32** [comment]
This should be fixed with the latest release.
